-- Tạo user
CREATE USER 'quy'@'%' IDENTIFIED BY 'quy';
GRANT ALL PRIVILEGES ON *.* TO 'quy'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'admin'@'%' IDENTIFIED BY 'haidang';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Tạo database
CREATE DATABASE game_db;

