// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/game.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "game";

export enum ElementType {
  BLOCKER = 0,
  POLYOMINOS = 1,
  EMPTY = 2,
  UNRECOGNIZED = -1,
}

export enum ElementSubType {
  BOX_BLOCKER = 0,
  HYDRANT_BLOCKER = 1,
  UNRECOGNIZED = -1,
}

export interface GameElement {
  elementType: ElementType;
  elementSubType: ElementSubType;
  width: number;
  height: number;
  /** "{}" hoặc json khác */
  elementProps: string;
}

export interface GameLevelData {
  gameName: string;
  gameId: string;
  levelId: string;
  cols: number;
  rows: number;
  elements: GameElement[];
}

export interface FindLevelRequest {
  levelId: string;
}

export interface FindLevelResponse {
  levelData: GameLevelData | undefined;
}

export interface CreateLevelRequest {
  levelData: GameLevelData | undefined;
}

export interface CreateLevelResponse {
  success: boolean;
  message: string;
  levelData: GameLevelData | undefined;
}

export const GAME_PACKAGE_NAME = "game";

export interface GameLevelServiceClient {
  findLevel(request: FindLevelRequest, metadata?: Metadata): Observable<FindLevelResponse>;

  createLevel(request: CreateLevelRequest, metadata?: Metadata): Observable<CreateLevelResponse>;
}

export interface GameLevelServiceController {
  findLevel(request: FindLevelRequest, metadata?: Metadata): Observable<FindLevelResponse>;

  createLevel(request: CreateLevelRequest, metadata?: Metadata): Observable<CreateLevelResponse>;
}

export function GameLevelServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findLevel", "createLevel"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GameLevelService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GameLevelService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GAME_LEVEL_SERVICE_NAME = "GameLevelService";
